from domain.exceptions import DomainException


class ValidationException(DomainException):
    pass
